var array = {
    etre : 'be was been',
    respecter : 'abide abode abode',
    survenir : 'arise arose arisen',
    reveiller : 'awake\tawoke\tawoken',
    supporter : 'bear\tbore\tborne',
    battre : 'beat\tbeat\tbeaten',
    devenir : 'become\tbecame\tbecome',
    engender : 'beget\tbegat / begot\tbegotten',
    commencer : 'begin\tbegan\tbegun',
    plier : 'bend\tbent\tbent',
    parier : 'bet\tbet\tbet',
    offrir : 'bid bade bidden',
    mordre : 'bite\tbit\tbitten',
    saigner : 'bleed\tbled\tbled',
    souffler : 'blow\tblew\tblown',
    casser : 'break\tbroke\tbroken',
    apporter : 'bring\tbrought\tbrought',
    lancer : 'cast\tcast\tcast',
    construire : 'build\tbuilt\tbuilt',
    bruler : 'burn\tburnt\tburnt',
    eclater : 'burst\tburst\tburst',
    acheter : 'buy\tbought\tbought',
    pouvoir : 'can\tcould\tcould',
    distribuer : 'deal dealt dealt',
    attraper : 'catch\tcaught\tcaught',
    gronder : 'chide chode chidden',
    choisir : 'choose\tchose\tchosen',
    accrocher : 'cling\tclung\tclung',
    venir : 'come\tcame\tcome',
    couter : 'cost\tcost\tcost',
    ramper : 'creep\tcrept\tcrept',
    couper : 'cut\tcut\tcut',
    creuser : 'dig\tdug\tdug',
    plonger : 'dive dived dove',
    faire : ' do did done',
    dessiner : 'draw\tdrew\tdrawn',
    rever : ' dream dreamt dreamt',
    boire : 'drink\tdrank\tdrunk',
    conduire : 'drive\tdrove\tdriven',
    habiter : 'dwell\tdwelt\tdwelt',
    manger : 'eat\tate\teaten',
    tomber : 'fall\tfell\tfallen',
    nourrir : 'feed\tfed\tfed',
    ressentir : 'feel\tfelt\tfelt',
    se_battre : 'fight\tfought\tfought',
    trouver : 'find\tfound\tfound',
    enfuir : 'flee\tfled\tfled',
    lancer2 : 'fling\tflung\tflung',
    voler : 'fly\tflew\tflown',
    interdire : 'forbid\tforbade\tforbidden',
    prevoir : 'forecast\tforecast\tforecast',
    presentir : 'foresee\tforesaw\tforeseen',
    oublier : 'forget\tforgot\tforgotten',
    pardonner : 'forgive\tforgave\tforgiven',
    abandonner : 'forsake\tforsook\tforsaken',
    geler : 'freeze\tfroze\tfrozen',
    obtenir : 'get\tgot\tgotten',
    donner : 'give\tgave\tgiven',
    aller : 'go\twent\tgone',
    moudre : 'grind\tground\tground',
    grandir : 'grow\tgrew\tgrown',
    pendre : 'hang\thung\thung',
    avoir : 'have\thad\thad',
    entendre : 'hear\theard\theard',
    cacher : 'hide\thid\thidden',
    taper : 'hit\thit\thit',
    tenir : 'hold\theld\theld',
    blesser : 'hurt\thurt\thurt',
    garder : 'keep\tkept\tkept',
    agenouiller : 'kneel\tknelt\tknelt',
    connaitre : 'know\tknew\tknown',
    poser : 'lay\tlaid\tlaid',
    mener : 'lead\tled\tled',
    pencher : 'lean\tleant\tleant',
    bondir : 'leap\tleapt\tleapt',
    apprendre : 'learn\tlearnt\tlearnt',
    quitter : 'leave\tleft\tleft',
    preter : 'lend\tlent\tlent',
    laisser : 'let\tlet\tlet',
    allonger : 'lie\tlay\tlain',
    allumer : 'light\tlit\tlit',
    perdre : 'lose\tlost\tlost',
    fabriquer : 'make\tmade\tmade',
    signifier : 'mean\tmeant\tmeant',
    rencontrer : 'meet\tmet\tmet',
    tondre : 'mow\tmowed\tmown',
    compenser : 'offset\toffset\toffset',
    surmonter : 'overcome\tovercame\tovercome',
    payer : 'pay\tpaid\tpaid',
    mettre : 'put\tput\tput',
    arreter : 'quit\tquit\tquit',
    lire : 'read\tread\tread',
    relayer : 'relay\trelaid\trelaid',
    dechirer : 'rend\trent\trent',
    debarrasser : 'rid\trid\trid',
    sonner : 'ring\trang\trung',
    lever : 'rise\trose\trisen',
    courir : 'run\tran\trun',
    scier : 'saw\tsaw\tsawn',
    dire : 'say\tsaid\tsaid',
    voir : 'see\tsaw\tseen'
}

$(".btn-answer").addClass("d-none");
var keys = Object.keys(array);

$( ".search-verb" ).click(function (){
    var randomVerb = keys[Math.floor(keys.length * Math.random())];
    var answer = array[randomVerb];
    $('.randomverb').empty().append(randomVerb);
    $('.answer').empty().append(answer).addClass('d-none');
    $(".btn-answer").removeClass("d-none");
})

$(".btn-answer").click(function (){
    $(".answer").removeClass("d-none");
})